---
  - name: Set chain-id for the CLIENT
    ini_file:
      path: "{{cosmospath}}/config/client.toml"
      section:
      option: "chain-id"
      value: '"{{chainid}}"'
    when: cosmospath !=  False
