---
  - name: Touch relevant files
    file:
      dest: "{{ item }}"
      state: touch
    with_items:
      - /root/.{{ prefix }}cosmos.env
      - /root/.{{ prefix }}cosmos.env.sh
    when: envvar != []

  - name: Create empty environment
    copy:
      mode: 0600
      dest: /root/.{{ prefix }}cosmos.env
      content: ""
    when: envvar == []

  - name: Configure COSMOS User environment /root/.{{ prefix }}cosmos.env
    replace:
      dest: /root/.{{ prefix }}cosmos.env
      regexp: ".*{{ item.var }}.*"
      replace: "{{ item.var }}='{{item.value}}'"
    with_items:
      - "{{ envvar }}"
    when: envvar != []
    register: cosmchange

  - name: Configure COSMOS User environment add or append /root/.{{ prefix }}cosmos.env
    lineinfile:
      dest: /root/.{{ prefix }}cosmos.env
      regexp: ".*{{ item.var }}.*"
      line: "{{ item.var }}='{{item.value}}'"
      state: present
    with_items:
      - "{{ envvar }}"
    when: envvar != []
    register: cosmaddorappend

  - name: Create empty environment for BASH
    copy:
      mode: 0600
      dest: /root/.{{ prefix }}cosmos.env.sh
      content: ""
    when: envvar == []

  - name: Configure COSMOS User environment for BASH /root/.{{ prefix }}cosmos.env.sh
    replace:
      dest: /root/.{{ prefix }}cosmos.env.sh
      regexp: "^.*{{ item.var }}.*"
      replace: "export {{ item.var }}='{{item.value}}'"
    with_items:
      - "{{ envvar }}"
    when: envvar != []
    register: bashchange

  - name: Configure COSMOS User environment for BASH add or append /root/.{{ prefix }}cosmos.env.sh
    lineinfile:
      dest: /root/.{{ prefix }}cosmos.env.sh
      regexp: "^.*{{ item.var }}.*"
      line: "export {{ item.var }}='{{item.value}}'"
      state: present
    with_items:
      - "{{ envvar }}"
    when: envvar != []
    register: bashaddorappend

  - name: Unify environment file
    shell: "TEMP=$(mktemp); sort -u {{item}} > ${TEMP}; cat ${TEMP}|tee {{item}}"
    with_items:
      - /root/.{{ prefix }}cosmos.env
      - /root/.{{ prefix }}cosmos.env.sh
    when: cosmchange.changed or cosmaddorappend.changed or bashchange or bashaddorappend

  - name: Configure User environment to load cosmos User Environment
    lineinfile:
      dest: /root/.bashrc
      create: true
      state: present
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - {regexp: "^source /root/.{{ prefix }}cosmos.env.sh", line: "source /root/.{{ prefix }}cosmos.env.sh"}
