- name: Create directory for ansible custom facts
  file:
    state: directory
    recurse: yes
    path: /etc/ansible/facts.d
  register: facts_dir_created

- name: Copy custom facts
  copy:
    src: "{{ item }}"
    dest: /etc/ansible/facts.d/
    owner: root
    group: root
    mode: 0755
  with_fileglob:
    - "facts/*.fact"
  register: facts_copied

- name: Copy custom facts (templates)
  template:
    mode: 0755
    src: "{{ item }}"
    dest: "/etc/ansible/facts.d/{{ item.split('/')[-1].split('.')[0] }}.fact"
  with_fileglob:
    - "facts/*.fact.jinja"
  register: facts_created

- name: "Re-run setup to use custom facts"
  setup: ~
  when: facts_copied.changed or facts_created.changed
