- name: Install helpful packages
  package: name={{ item }} state=present
  with_items:
    - powerline

  ignore_errors: true

- name: link powerline so is loaded Debian
  file:
    dest: /etc/profile.d/powerline.sh
    force: yes
    state: link
    src: /usr/share/powerline/bindings/bash/powerline.sh
  when: os == 'debian'

- name: link powerline so is loaded Fedora
  file:
    dest: /etc/profile.d/powerline.sh
    force: yes
    state: link
    src: /usr/share/powerline/bash/powerline.sh
  when: os == 'fedora'

- name: Configure User environment
  lineinfile:
    dest: /root/.bashrc
    create: true
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
        regexp: "^source /etc/profile.d/powerline.sh",
        line: "source /etc/profile.d/powerline.sh",
      }
