- name: Include task for individual base commands
  include_tasks: "{{item}}"
  with_fileglob:
    - "base/*.yaml"

- name: Stop monit if unused
  service:
    name: monit
    state: stopped
  when: monit == False
