---
  - name: Delete cosmos query rewards command
    file:
      dest: "/root/{{ prefix }}query-rewards"
      state: absent
    when: createcommands != True and validator != True

  - name: Create cosmos query rewards command
    copy:
      mode: 0700
      dest: "/root/{{ prefix }}query-rewards"
      content: |
        #!/usr/bin/env bash
        . /root/.{{ prefix }}cosmos.env.sh
        CHAINCOMMAND="{% if cosmovisor != False %}{{ cosmospath }}/cosmovisor/current/bin/{{chaincommand}}{% else %}/root/go/bin/{{chaincommand}}{% endif %}"
        ${CHAINCOMMAND} query distribution rewards {{ address }} {{ extrabin }} {% if node != False %}--node {{ node }}{% endif %}  $*
        ${CHAINCOMMAND} query distribution commission {{ valaddress }} {{ extrabin }} {% if node != False %}--node {{ node }}{% endif %}  $*
    when: createcommands == True and validator == True
